calaldees/KaraKara

.gitignore, .travis.yml, Makefile, processmedia2/Makefile, processmedia2/tests/source/Makefile
If you activate the travis-ci webhook in the settings menu, this will provide you with continuous testing of processmedia2 and the KaraKara website. 
Possible improvements:
* Run all the tests and report the error at the end
* Currently it won't run the website tests if the processmedia2 tests fail.
=> Travis testing of processmedia2 and website

website/karakara/static/css/print_list.css, website/karakara/templates/html/track_list.mako
The same info that's in the footer on the big screen
=> Show "Join at XXX - Queue is YYY" instructions on the track list

.github/workflows/browser2.yml, .github/workflows/dashboard.yml, .github/workflows/nginx.yml, .github/workflows/player2.yml, .github/workflows/postgres.yml, .github/workflows/processmedia2.yml, .github/workflows/website.yml
Add github workflows to publish docker images for each project
Needs the repository to have DOCKER_USERNAME and DOCKER_PASSWORD set
Possible next step: run unit tests and only push a new build if they pass
=> Auto build docker images

.github/workflows/test_cypress.yml
Cypress workflow now always store artifacts
=> Updated test workflow to artifact on fail

api_queue/api_queue/queue.py, api_queue/api_queue/server.py, api_queue/tests/conftest.py, api_queue/tests/test_app.py
I want to change the queue settings o.o
=> `PUT settings.json` to update settings

browser2/src/browser.d.ts, browser2/src/browser.ts, browser2/src/effects.ts, browser2/src/screens/_common.tsx, browser2/src/screens/printable_list.tsx, browser2/src/subs.ts, browser2/src/track_grouper.ts, browser2/src/utils.ts, browser2/tests/track_grouper.test.ts, browser2/tsconfig.json
=> [br2] no implicit any

player2/src/effects.ts, player2/src/player.d.ts, player2/src/player.ts, player2/src/screens/_common.tsx, player2/src/screens/podium.tsx, player2/src/screens/preview.tsx, player2/src/screens/root.tsx, player2/src/screens/settings.tsx, player2/src/subs.ts, player2/tsconfig.json
=> [pl2] no implicit any

.github/workflows/player2.yml
=> [pl2] fix build dir

browser2/package-lock.json, browser2/package.json, browser2/src/subs.ts
[br2] u8-mqtt, see #149 (250KB -> 75KB)
=> [br2] u8-mqtt, see #149 (250KB -> 75KB)

player2/package-lock.json, player2/package.json, player2/src/subs.ts
[pl2] u8-mqtt, see #149 (220KB -> 40KB)
=> [pl2] u8-mqtt, see #149 (220KB -> 40KB)

browser3/package-lock.json, browser3/package.json, browser3/src/providers/server.tsx
[br3] new useServerTime version
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/calaldees/KaraKara/pull/174).
* #175
* __->__ #174
=> [br3] new useServerTime version

browser3/src/screens/tracks.tsx
[br3] only set defaultValue rather than value in search box, fixes #208
=> [br3] only set defaultValue rather than value in search box, fixes #208

nginx/nginx.conf
[nginx] use x-real-ip header, fixes #205
=> [nginx] use x-real-ip header, fixes #205

browser3/src/screens/__tests__/printable.cye.ts, browser3/src/screens/tracks.tsx
[br3] s/Printable Tracklist/Printable QR Code/
=> [br3] s/Printable Tracklist/Printable QR Code/

api_queue/api_queue/server.py
[api] avoid some deprecation warnings
=> [api] avoid some deprecation warnings

browser3/src/screens/tracks.tsx
[br3] only show bookmarks which would be visible with the current queue, fixes #216
=> [br3] only show bookmarks which would be visible with the current queue, fixes #216

processmedia3/.mypy.ini, processmedia3/Dockerfile, processmedia3/pyproject.toml, processmedia3/requirements.test.txt, processmedia3/requirements.txt
[pm3] various python-tool config files -> one pyproject.toml
=> [pm3] various python-tool config files -> one pyproject.toml

processmedia3/Dockerfile
[pm3] ffmpeg 6.1
---
[//]: # (BEGIN SAPLING FOOTER)
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/calaldees/KaraKara/pull/221).
* __->__ #221
* #220
=> [pm3] ffmpeg 6.1

api_queue/api_queue/server.py, api_queue/pyproject.toml
[api] bump to aiomqtt 2.0
---
[//]: # (BEGIN SAPLING FOOTER)
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/calaldees/KaraKara/pull/218).
* #219
* __->__ #218
=> [api] bump to aiomqtt 2.0

api_queue/Dockerfile, api_queue/api_queue/server.py, api_queue/pyproject.toml
[api] python 3.12
---
[//]: # (BEGIN SAPLING FOOTER)
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/calaldees/KaraKara/pull/219).
* __->__ #219
* #218
=> [api] python 3.12

processmedia3/README.md, processmedia3/lib/subtitle_processor.py, processmedia3/tests/subs/verse_gap.srt, processmedia3/tests/subs/verse_gap.vtt
`./lib/subtitle_processor.py input.srt output.vtt`
=> [pm3] make subtitle_processor an executable script to test generation easier

player3/src/screens/title.tsx
[pl3] avoid duplicate thumb on splash
=> [pl3] avoid duplicate thumb on splash

processmedia3/tests/test_main.py
=> [pm3] update tests

processmedia3/lib/kktypes.py
[pm3] mark .webm as a valid input video type
=> [pm3] mark .webm as a valid input video type

.devcontainer/Dockerfile, processmedia3/Dockerfile, processmedia3/README.md, processmedia3/lib/encoders.py
=> [pm3] ffmpeg 7.0

processmedia3/main.py
[pm3] add units to progress bars
=> [pm3] add units to progress bars

processmedia3/main.py
[pm3] test-encode command to encode a single file
=> [pm3] test-encode command to encode a single file

processmedia3/README.md, processmedia3/lib/encoders.py
Show the encoding progress per output file, since each file can take several minutes
=> [pm3] ffmpeg progress bars

processmedia3/lib/encoders.py
With these flags it only shows the progress report, warnings, and errors
=> [pm3] Have ffmpeg be less spammy so it's easier to see errors in the output

processmedia3/get_example_media.py, processmedia3/lib/encoders.py, processmedia3/lib/file_abstraction.py, processmedia3/lib/kktypes.py, processmedia3/lib/subtitle_processor.py, processmedia3/lib/target.py, processmedia3/lib/track.py, processmedia3/main.py, processmedia3/tests/test_main.py, processmedia3/tests/test_subtitle_processor.py
---
[//]: # (BEGIN SAPLING FOOTER)
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/calaldees/KaraKara/pull/298).
* #299
* __->__ #298
=> [pm3] more consistent typing
